# Generated by Django 5.2 on 2025-09-20 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('domain', models.CharField(max_length=255)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('security_checks', models.JSONField(default=dict)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='analyzer.uploadedpdf')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_action', models.URLField(max_length=2000)),
                ('form_method', models.CharField(max_length=10)),
                ('form_fields', models.JSONField()),
                ('is_phishing', models.BooleanField(default=False)),
                ('analysis_results', models.JSONField(default=dict)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='analyzer.uploadedpdf')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('official_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('domain_info', models.JSONField(default=dict)),
                ('context', models.TextField()),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='analyzer.uploadedpdf')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_verdict', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('details', models.JSONField()),
                ('company_verification', models.JSONField(default=dict)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='analyzer.uploadedpdf')),
            ],
        ),
    ]
